version: "3.9"

services:
  domainmonitor:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST:-db} # should be same as the database service name
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-postgres}
    depends_on:
      - db
    tty: true

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./conf/nginx/http.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - domainmonitor

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
